version: '3.8'

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jekyll
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    command: bundle exec jekyll serve --host 0.0.0.0 --watch
    environment:
      - JEKYLL_ENV=development

