language: ja
timezone: Asia/Tokyo

title: nao2bs.net
description: >
  プログラミング関係のメモを書くブログです。
baseurl: ""
url: "https://nao2bs.net"

author:
  name: NAO
  email: nao2bs@gmail.com
  github: nao2bs
  twitter: nao2bs

paginate: 5
paginate_path: page:num

sass:
  style: compressed
  # style: expanded

exclude:
  - node_modules
  - vendor

excerpt_separator: "<!--more-->"

# safe: false

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-admin

jekyll_admin:
  basic_auth:
    username: "admin" # Set your desired username
    password: "password" # Set your desired password
