source "https://rubygems.org"

# gem 'jekyll-watch'
# gem 'jekyll-paginate'
# gem 'jekyll-feed'
# gem 'kramdown-parser-gfm'
# gem 'webrick', '~> 1.7'
# gem 'rack', '~> 2.2'
# gem 'jekyll-admin', group: :jekyll_plugins



gem 'jekyll', '~> 4.3'
gem 'jekyll-watch'
gem 'jekyll-paginate'
gem 'jekyll-feed'
gem 'kramdown-parser-gfm'
gem 'webrick', '~> 1.7'
gem 'rack', '~> 2.2'
gem 'jekyll-admin', '~> 0.11.1', group: :jekyll_plugins
gem 'sinatra', '~> 2.0'
gem 'sinatra-contrib', '~> 2.0'